### ISSUE TITLE
Issue with caffeine not loading other packages correctly when it refreshes. 

### ISSUE THREAD

**Issue by RoshanJafri** [mikebronner/laravel-caffeine#135]
## Behavior
When caffeine refreshes the session, other npm packages don't load correctly.
I have the package [voerro/vue-tagsinput](https://github.com/voerro/vue-tagsinput) along with caffeine. Everything's fine until caffeine auto refreshes page session, when it does refresh the tags input component doesn't load correctly, the css is missing ( no error in console  either )
This is what it looks when caffeine refreshes session: 
![image](https://user-images.githubusercontent.com/47788416/115103467-8a90e200-9f6b-11eb-878b-56a31db45e36.png)

This is what it looked like before caffeine refreshed the session, what it should look like after refresh too:
![image](https://user-images.githubusercontent.com/47788416/115103528-eeb3a600-9f6b-11eb-8e3d-f52b57fb570f.png)

And when I try to type something in the input 
![image](https://user-images.githubusercontent.com/47788416/115103473-9da3b200-9f6b-11eb-8478-1d80b8f288ff.png)

This works fine before caffeine refreshes the session. Any help?

## Environment
- PHP Version: 7.4.11
- Laravel Version: 7.29
- LaravelCaffeine Version: 7.0.2

**Comment by mikebronner** [comment]
Closing for now. If this is still an issue, please provide a GitHub repo that replicates this issues.
