### ISSUE TITLE
Should fix when the device is in sleep mode

### ISSUE THREAD

**Issue by AnnaBelka** [mikebronner/laravel-caffeine#137]
Hello.
I have a problem when my laptop is in sleep, after waking up I see an error connecting to the Internet. I found out that when this condition is met, 

>  
      if ({{ $ageCheckInterval }} ) {
                setInterval(function () {
                    if (new Date() - lastCheck >= {{ $ageCheckInterval + $ageThreshold }}) {
                        location.reload(true);
                    }
                }, {{ $ageCheckInterval }});
         }

my page starts to reload, but since the laptop is in sleep mode, then it does not have access to the Internet, respectively. 

I found a solution to this problem in correcting this part of the code 

>   
    if ({{ $ageCheckInterval }} > 0) {
        setInterval(function () {
            if (new Date() - lastCheck >= {{ $ageCheckInterval + $ageThreshold }}) {
                setTimeout(function () {
                    location.reload(true);
                },  Math.max(0, {{ $ageCheckInterval }} - 500) )
            }
        }, {{ $ageCheckInterval }});
    }

When I added setTimeout I stopped getting infinite page reload and further connection error. Now my page reloads when my laptop wakes up.

**Comment by mikebronner** [comment]
This should now be in the latest release.
