### ISSUE TITLE
The included script is added in a place where it affects my site layout

### ISSUE THREAD

**Issue by blorange2** [mikebronner/laravel-caffeine#139]
## Expected Behavior

Package should not affect overall site layout

## Acutal Behavior

The package adds its scripts but also modifies my layout.

## Environment
- PHP Version: 7.4
- Laravel Version: ^7.0
- LaravelCaffeine Version: 7

## Before

![image](https://user-images.githubusercontent.com/13929733/148939648-772a5fa4-ef63-4f43-a8e3-4a3bef2e54db.png)

From line 369 where the end of the `<main>` is.

## After

![image](https://user-images.githubusercontent.com/13929733/148940096-726bf55a-bd03-408d-a82f-1ea2b38c1e9f.png)

**Comment by mikebronner** [comment]
this should no longer be happening.
