### ISSUE TITLE
Need a reflash

### ISSUE THREAD

**Issue by MoogyG** [mikebronner/laravel-caffeine#97]
I have a user form where he can upload an avatar and fill other fields.

If he uploads an image but the request doesn't pass the validation on an other field, he don't have to upload again the image, I store it the first time and flash the storage path to display it and use the stored image the next valid request.

As drip is just here to keep session alive, and should not modify session state, don't you think we should do a "reflash" before sending the 204 response?

**Comment by mikebronner** [comment]
Not sure about this, I will have to think about it.

**Comment by Yahav** [comment]
@MoogyG This sounds important, i don't understand though how this will affect the flashed data? flashed data will returned with the very next response, that is before a drip will occur. so how the drip is altering the session flashed data?

**Comment by MoogyG** [comment]
In my case the drip occurs before the user submits the form a second time, so the flashed data is consumed and removed.

**Comment by mikebronner** [comment]
@MoogyG Thanks for providing additional details. It sounds like the flash methodology should not flash info out to json requests, but only to web requests.

I will try adding the appropriate headers to Caffeine to make sure Laravel doesn't think it's a web request.

**Comment by Yahav** [comment]
> @MoogyG Thanks for providing additional details. It sounds like the flash methodology should not flash info out to json requests, but only to web requests.
> 
> I will try adding the appropriate headers to Caffeine to make sure Laravel doesn't think it's a web request.

Actually you're quite wrong, flashed data is used in many cases, one example is validation errors, when dealing with ajax forms you'll get validation errors flashed as json - eg. json requests considered web requests as well..

**Comment by mikebronner** [comment]
Closing this for now. If this is still an issue, please provide a GitHub repo that replicates the issues.
